#!/usr/bin/env php
<?php

require_once 'vendor\autoload.php';
// Create the Application
$application = new Symfony\Component\Console\Application;

// register all command
$application->add(new Application\Commands\MigrateCommand);
$application->add(new Application\Commands\MigrationCommand);
$application->add(new Application\Commands\RollbackCommand);
$application->add(new Application\Commands\SeedCommand);

// Run it
$application->run();
