#!/usr/bin/env php
<?php

require_once 'vendor\autoload.php';
// Create the Application
$application = new Symfony\Component\Console\Application;

// register all command
$application->add(new App\Command\MigrateCommand);
$application->add(new App\Command\MigrationCommand);
$application->add(new App\Command\RollbackCommand);

// Run it
$application->run();
